temporalio/omes

- .github/workflows/ci.yml
- cmd/build_worker_image.go
- cmd/cmdoptions/client.go
- cmd/main.go
- cmd/prepare_worker.go
- cmd/run_scenario.go
- cmd/run_worker.go
- dockerfiles/go.Dockerfile
- dockerfiles/python.Dockerfile
- go.mod
- go.sum
- workers/go/go.sum
Added `build-worker-image` command. Intentionally don't have a bunch of `git` commands or support `push`ing at this time, though we can add later if we must (though we may find cloning a repo and pushing a docker image to be better suited for the environment and not the CLI).
> Basic worker image building

- README.md
- cmd/run_worker.go
- go.mod
- loadgen/generic_executor.go
- loadgen/kitchen_sink_executor.go
- loadgen/scenario.go
- scenarios/workflow_on_many_task_queues.go
- workers/go/worker/worker.go
- workers/python/main.py
Added a new `workflow_on_many_task_queues` scenario and support for running many workers in a single worker process.
For example to run scenario with 500 workflows across 20 task queues in Go using embedded server and running worker at the same time, you'd run
```
go run ./cmd run-scenario-with-worker --scenario workflow_on_many_task_queues --language go --embedded-server --iterations 500 --option task-queue-count=20 --task-queue-suffix-index-end 19
```
Of course this could be broken out to just, say, 2 workers running 10 each against existing server:
```
go run ./cmd run-worker --server-address 1.2.3.4:7233 --scenario workflow_on_many_task_queues --language go --run-id my-run --task-queue-suffix-index-end 9
```
```
go run ./cmd run-worker --server-address 1.2.3.4:7233 --scenario …
```
> Multi-task-queue Scenario

- loadgen/generic_executor.go
- loadgen/generic_executor_test.go
- loadgen/scenario.go
- scenarios/state_transitions_steady.go
- scenarios/workflow_on_many_task_queues.go
- workers/go/workflows/kitchen_sink.go
Created new steady state transition scenario. This requires duration and requires a `state-transitions-per-second` scenario option. This is a naive implementation that just runs a basic workflow once to get the count, and then runs that as many times as necessary to run that count. There is no backpressure nor is there any logic in checking whether server state transitions is actually matching this.
To try out with embedded server/worker, clone branch and run:
go run ./cmd run-scenario-with-worker --scenario state_transitions_steady --language go --embedded-server --duration 30s --option state-transitions-per-second=200
This will output logs like:
```
2023/08/28 10:47:58 INFO  Starting DevServer ExePath C:\Users\user\AppData\Local\Temp\temporal-cli-go-sdk-1.22.1.exe Args [server start-dev …
```
> Naive steady state transition scenario

- cmd/cmdoptions/client.go
- cmd/run_worker.go
- workers/python/main.py
`--tls` flag was added.
To allow connecting to Temporal clusters that use TLS but not require client certificates.
> Introduce --tls flag

- cmd/cmdoptions/worker.go
- cmd/run_worker.go
- workers/go/worker/worker.go
- workers/python/main.py
The following flags were added:
```
--worker-max-concurrent-activity-execution-size int        Max concurrent activity execution size
--worker-max-concurrent-activity-task-pollers int          Max concurrent activity task pollers
--worker-max-concurrent-workflow-task-execution-size int   Max concurrent workflow task execution size
--worker-max-concurrent-workflow-task-pollers int          Max concurrent workflow task pollers
```
To be able to set up workers according to [the recommendations](https://docs.temporal.io/dev-guide/worker-performance#configuration).
> Introduce flags for setting worker options such as task poller counts and concurrent execution limits

- .github/workflows/docker-images.yml
- dockerfiles/typescript.Dockerfile
- checkout submodules
- Ignore linter complaint about `cd` in dockerfile
> Fix typescript docker build pipeline

- .gitmodules
This is convenient when building a docker image. Specifically, this PR helps Omes CICD work https://github.com/temporalio/saas-cicd/pull/558.
> Use https URL for submodule

- loadgen/fuzz_executor.go
In some contexts (e.g. CICD control plane workers) a client of the omes Go library will want to build the `kitchen-sink-gen` executable at (docker image) build time. However, currently omes invokes `kitchen-sink-gen` via `cargo run` at run-time.
Support passing this as  scenario-specific option named `kitchen-sink-gen`. Its value is either the name of the executable (to be resolved via `$PATH`) or an absolute path. This is usable via the CLI as `--option=kitchen-sink-gen=my-executable`, or by a library client as 
```go
ScenarioOptions: map[string]string{
"kitchen-sink-gen": "my-executable",
},
```
```
go run ./cmd run-scenario --scenario fuzzer_example --run-id 1234 --duration 10s --option kitchen-sink-gen=$PWD/ksg
```
where
```
$ cat ksg
#!/bin/bash
echo using pre-built kitchen-sink-gen …
```
> Allow pre-built kitchen-sink-gen executable

- loadgen/kitchen-sink-gen/src/main.rs
When using the same RNG seed output should be identical. We're using `unstructured.choose()`, which will make the same choice on the same input, but we're passing it input from `HashMap.keys()` which varies in a way that doesn't respect our RNG seed.
Sort the keys before sampling from them.
I've also removed an used struct field.
The protobuf output is still not identical between runs using the same seed
```
$ md5sum <(cargo run -- generate --explicit-seed=12345 2>/dev/null) <(cargo run -- generate --explicit-seed=12345 2>/dev/null)
0e6a07381e53be30917f70469f67b8e0  /dev/fd/11
0cbf879a9a16bd8cb86c8abd1c0a5dc4  /dev/fd/12
```
I believe that is due to non-deterministic serialization of the `WorkflowState` HashMap. Even if that has no consequences for the workflow generation, it would be …
> Fix non-determinism due to HashMap

- workers/python/main.py
The prometheus server is started by the core bridge nowadays. This PR gets rid of some draft code we had that was starting a server directly in Python. Without this PR there are errors in the python code and a port conflict that can be reproduced with
```
docker build -f dockerfiles/python.Dockerfile -t omes-python .
docker run -e RUST_BACKTRACE=full omes-python \
--scenario workflow_with_single_noop_activity \
--run-id local-test-run \
--language python \
--namespace default \
--server-address=host.docker.internal:7233 \
--worker-prom-listen-address=127.0.0.1:9090
```
> Fix Python worker prometheus exporter

- loadgen/kitchen-sink-gen/src/main.rs
- scenarios/fuzzer.go
This PR has two major changes:
* Change the empty payload type used as a protobuf message to `binary/protobuf` instead of `json/plain` because some languages json dataconverter cannot handle protobuf messages
* Support passing config options the fizzer
> Omes empty payload

- loadgen/scenario.go
- loadgen/throughputstress/throughput_stress.go
- scenarios/throughput_stress.go
- workers/go/throughputstress/workflow.go
This makes workflow end to end latency more informative by avoiding dilution with un-optimisable time.
> Add the ability to skip sleeps.

- cmd/cmdoptions/client.go
Add more TLS options 
Add the tls options to support Private Link testing
1. Closes 
> Add more TLS options 

- loadgen/kitchensink/helpers.go
- workers/go/throughputstress/activities.go
Without this change, there are errors like this:
```
$ go run ./cmd run-scenario --scenario fuzzer --run-id $runid --duration 10s
2024-07-15T10:56:56.371-0400    ERROR   loadgen/scenario.go:242 Client actions failed: failed \
to execute client action do_update: \
{do_actions:{do_actions:{actions:{exec_activity:{delay:{nanos:177000000} \
start_to_close_timeout:{seconds:5} remote:{cancellation_type:WAIT_CANCELLATION_COMPLETED} \
awaitable_choice:{abandon:{}}}}}}}: \
WaitForStage must be specified        {"iteration": 4}
...
```
> Add required wait stage to Go client calls

- loadgen/scenario.go
Omes is supposed to replicate user behavior to generate load on the server. Registering search attributes doesn't belong in the hot path, it should be done as a separate setup step.
See also: https://github.com/temporalio/omes/issues/93
> Remove search attribute registration before starting every workflow

- loadgen/fuzz_executor.go
Evidence this change is correct:
Output with invalid executable path:
> 2024-07-25T22:57:44.753-0400    FATAL   cmd/run_scenario_with_worker.go:20      scenario failed: failed scenario: failed to run rust generator (xxx generate --output-path last_fuzz_run.proto): exec: "xxx": executab
le file not found in $PATH
> Include failed command in error message

- .github/workflows/docker-images.yml
- cmd/build_worker_image.go
Allows the image building workflow to use a reference to an SDK repo to build an image with it as of that commit
> Allow building worker images from local SDK paths

- cmd/run_scenario.go
I tested that it compiled and the log message was formatted appropriately when I created a fake error:
```go
err = errors.New("an error")
```
```
WARN    cmd/run_scenario.go:139 Error ignored when registering search attributes: an error
```
> Warn when registering search attributes fails

- README.md
- cmd/prepare_worker.go
- More thoroughly document dependencies in the README
- Teach prepare_worker how to rebuild the TypeScript worker (which must be done manually and is currently undocumented)
> Small first-run experience improvements

- .github/workflows/ci.yml
- README.md
- workers/dotnet/Temporalio.Omes.csproj
* Update .NET SDK 1.3.1
* Added https://github.com/temporalio/sdk-core/issues/803 to trophy case
> Update .NET SDK to 1.3.1

- workers/python/kitchen_sink.py
https://python.temporal.io/temporalio.workflow.html#wait
> Use deterministic version of asyncio.wait

- .github/workflows/ci.yml
- workers/java/build.gradle
- workers/java/io/temporal/omes/KitchenSinkWorkflowImpl.java
Add Upsert memo support for Java
> Add upsert memo support for Java

- README.md
- loadgen/throughputstress/throughput_stress.go
- scenarios/throughput_stress.go
- workers/go/throughputstress/operations.go
- workers/go/throughputstress/workflow.go
- workers/go/worker/worker.go
Added three new steps to the throughput_stress scenario:
1. Sync Nexus operation
2. Async Nexus operation
3. Async Nexus operation with cancelation
See added instructions in the README for running with Nexus.
> Add Nexus to throughput_stress scenario

- loadgen/scenario.go
- scenarios/throughput_stress.go
Added timeout for throughput stress run.
Workflow execution timeout was hard-coded. I need it to either be zero or a higher value for when testing delayed workflow processing.
1. Closes 
> Add iteration timeout to throughput_stress

- dockerfiles/go.Dockerfile
- go.mod
- scenarios/throughput_stress.go
- workers/go/go.mod
Allow to customize Workflow ID in throughputStress scenario.
For our test pipeline, I need to start multiple Omes runs (since I don't want to abort the entire pipeline run if one fails).
But changing the Omes RunID or Scenario is not possible, as that is used to compute the task queue (Workers are deployed separately and rely on the task queue identifier).
Thus, to avoid Workflow ID conflicts, generating unique Workflow IDs is needed.
1. Closes 
> Customizable throughputStress Workflow IDs

- README.md
- loadgen/helpers.go
- loadgen/helpers_test.go
- loadgen/throughputstress/throughput_stress.go
- scenarios/throughput_stress.go
- workers/go/throughputstress/activities.go
Follow-up to https://github.com/temporalio/omes/pull/137.
Adds more distribution types: normal, zipf and uniform.
Sorry for breaking the JSON schema already after I just merged it yesterday, but I doubt anyone is using this yet.
For testing fairness, we'll need the ability to test millions of distinct keys. The discrete distribution alone is insufficient for that.
```
echo '{"patterns_dist": {"type":"discrete", "weights": {"1":1, "5":9}}, "pattern_durations_dist": {"1": {"type":"discrete", "weights": {"1s": 1}}, "5": {"type":"discrete", "weights": {"1s": 1, "5s": 4}}}}' > input.json
go run ./cmd run-scenario-with-worker \
--scenario throughput_stress --run-id omes1 --language go \
--option sleep-activity-per-priority-json=@input.json
```
> Multiple distribution types

- loadgen/helpers.go
- loadgen/scenario.go
- scenarios/throughput_stress.go
- workers/go/throughputstress/workflow.go
Added affordances to make the throughputStress scenario resumable.
If the throughputStress scenario crashes (e.g. pod restarted), we want to be able to continue where it left off.
Started Omes with
```
go run ./cmd run-scenario-with-worker \
--scenario throughput_stress \
--run-id omes \
--language go \
--iterations 2 \
--max-concurrent 1 \
--option internal-iteratios-timeout=1s \
--option visibility-count-timeout=5s
```
Once the first iteration succeeded, I stopped it and then ran (numbers taken from the logged status update):
```
go run ./cmd run-scenario-with-worker \
--scenario throughput_stress \
--run-id omes \
--language go \
--iterations 2 \
--option internal-iteratios-timeout=1s \
--option visibility-count-timeout=5s \
--option internal-iterations-resume-from=1 \
--option …
```
> Make throughputStress resumable

- workers/go/throughputstress/workflow.go
Mostly this change ensures that we only update the `params` variable and have that serve as the source of truth for the workflow state.
I also changed the workflow to wait for the self signal to be received before completing (which was the original reason I took this on).
> throughput_stress: Assert expected signal is received at least once, slight refactoring

- workers/go/throughputstress/operations.go
Replace `temporalnexus.NewSyncOperation` with `nexus.NewSyncOperation`
`temporalnexus.NewSyncOperation` is deprecated and no longer available.
1. Closes 
> Replace temporalnexus.NewSyncOperation with nexus.NewSyncOperation

- workers/go/throughputstress/workflow.go
WISOTT
Use workflow timeout instead. 
Activity timeouts were too aggressive and caused pipeline failures when encountering minimal server disruption.
1. Closes 
> Remove throughputstress activity timeouts

- loadgen/helpers.go
- loadgen/helpers_test.go
- loadgen/throughputstress/throughput_stress.go
- workers/go/throughputstress/workflow.go
Using a random seed instead of wrapping randomly generated output in `workflow.SideEffect`.
`workflow.SideEffect` doesn't work with arrays of proto messages. The serialization breaks the result in this case, as one of the fields is not JSON exportable.
**Reviewer: Looks bigger than it really is. I marked the two actual changes.**
> Fix SleepActivityConfig

- scenarios/throughput_stress.go
Added retries for the Workflow Start.
When we run the throughput_stress scenario with faults in our CICD pipeline, the workflow start can fail. Omes will abort the run immediately. CICD will restart Omes and resume.
All that creates unnecessary delays and noise. Internal retries mitigate that.
1. Closes 
> throughput_stress retries

- cmd/build_worker_image.go
- cmd/cmdoptions/scenario.go
- cmd/cmdoptions/sdk.go
- cmd/prepare_worker.go
- cmd/run_scenario.go
- cmd/run_scenario_with_worker.go
- cmd/run_worker.go
- workers/build.go
- workers/run.go
Move code to build and start worker from `main` into `workers` package.
No behavior change expected.
Reusability. The [kitchensink parity test](https://github.com/temporalio/omes/pull/180) needs to start workers for testing.
1. Closes 
> Re-usable Worker build and start

- .github/workflows/ci.yml
- .github/workflows/docker-images.yml
- .gitignore
- README.md
- cmd/build_worker_image.go
- cmd/cmdoptions/scenario.go
- cmd/prepare_worker.go
- cmd/run_scenario.go
- cmd/run_scenario_with_worker.go
- cmd/run_worker.go
- dockerfiles/dotnet.Dockerfile
- dockerfiles/go.Dockerfile
- dockerfiles/java.Dockerfile
- dockerfiles/python.Dockerfile
- dockerfiles/typescript.Dockerfile
- go.mod
- go.sum
- loadgen/helper_historyrequire.go
- loadgen/kitchen_sink_executor_test.go
- scripts/helpers/build-worker.sh
- scripts/install-dotnet.sh
- workers/build.go
- workers/dotnet/Temporalio.Omes/KitchenSinkWorkflow.cs
- workers/go/go.mod
- workers/go/go.sum
- workers/go/kitchensink/kitchen_sink.go
- workers/java/io/temporal/omes/KitchenSinkWorkflowImpl.java
- workers/run.go
- workers/typescript/.eslintignore
- workers/typescript/src/workflows/kitchen_sink.ts
Framework for checking kitchensink actions across SDKs.
(more tests to be added later ...)
To ensure actions are supported correctly and comprehensively; and document missing implementations.
Especially for new actions this helps ensure you've implemented them correctly.
1. Closes 
> Kitchensink test

- .github/workflows/ci.yml
- README.md
- go.mod
- go.sum
- loadgen/helper_historyrequire.go
- loadgen/helper_testenv.go
- loadgen/kitchen_sink_executor_test.go
- loadgen/kitchensink/client_action_executor.go
- loadgen/kitchensink/helpers.go
- loadgen/scenario.go
- scenarios/throughput_stress_test.go
- workers/build.go
- workers/go/go.mod
- workers/go/go.sum
- workers/log.go
- workers/run.go
Prelude for https://github.com/temporalio/omes/pull/179:
- adds partial history matching (when full matching won't work)
- scopes build logs to test run
- runs kitchen sink tests in parallel
- fixes data race
- adds new end-to-end ThroughputStress test
Improve test experience.
1. Closes 
> Extend test helpers

- loadgen/kitchen_sink_executor_test.go
- workers/dotnet/Temporalio.Omes/ClientActionsExecutor.cs
- workers/python/client_action_executor.py
- workers/typescript/src/client-action-executor.ts
Follow-up to https://github.com/temporalio/omes/pull/179 to include other SDKs.
Adds new "Client" ActivityType to execute client actions (e.g. Update, Signal) from a workflow activity to TS, .NET and Python.
The client action executor implementations were all modeled after the Go one.
---
ℹ️  Concurrent execution of the client actions is out of scope for this PR.
🫘 I couldn't get Java to work; it's out of scope for this PR now. Sorry.
⚠️ The ClientActionExecutors were mostly AI generated - with lots of manual pruning and fixing - but I can't quite vouch for them being 100% idiomatic. 
Narrow kitchensink support gap to Go.
1. Closes 
> Kitchensink client activity [Python, TS, .NET]

- loadgen/generic_executor.go
- loadgen/helpers.go
- loadgen/kitchen_sink_executor.go
- loadgen/kitchen_sink_executor_test.go
- loadgen/scenario.go
- scenarios/fixed_resource_consumption.go
- scenarios/throughput_stress.go
- scenarios/throughput_stress_test.go
- workers/test_env.go
Fix resume bug.
The `OnComplete` hook wasn't always invoked properly leading to under-counting the completed iterations.
1. Closes 
> Fix throughput_stress resume

- README.md
- cmd/cli/cleanup_scenario.go
- cmd/cli/list_scenarios.go
- cmd/cli/main.go
- cmd/cli/prepare_worker.go
- cmd/cli/run_scenario.go
- cmd/cli/run_scenario_with_worker.go
- cmd/cli/run_worker.go
- cmd/cli/util.go
- cmd/cli/util_nonwindows.go
- cmd/cli/util_windows.go
- cmd/clioptions/client.go
- cmd/clioptions/logging.go
- cmd/clioptions/metrics.go
- cmd/clioptions/scenario.go
- cmd/clioptions/sdk.go
- cmd/clioptions/worker.go
- cmd/clioptions/zap_adapter.go
- cmd/dev/build_helper.go
- cmd/dev/build_worker_image.go
- cmd/main.go
- loadgen/kitchen_sink_executor_test.go
- loadgen/scenario.go
- scenarios/ebb_and_flow_test.go
- scenarios/throughput_stress_test.go
- workers/build.go
- workers/go/worker/worker.go
- workers/run.go
- workers/test_env.go
- workers/test_workers.go
Moved CLI commands to exported package:
- new package `cli`
- renamed `cmdoptions` to `clioptions` to match
This allows writing a thin Omes CLI wrapper application that defines its own scenario; but still provide all the Omes CLI options as if it was an "internal" scenario.
Of course this only works if the scenario uses the kitchensink executor.
```go
package main
import (
"github.com/temporalio/omes/cmd/cli"
_ "examples/custom-scenario/scenarios" // register our custom scenarios
)
func main() {
cli.Main()
}
```
Using Omes programmatically as a library was already possible; but the CLI use case was not.
1. Closes 
> Reusable CLI
