temporalio/omes

- .gitmodules
- dockerfiles/python.Dockerfile
- workers/proto/kitchen_sink/activity.proto
- workers/proto/kitchen_sink/child_workflow.proto
- workers/proto/kitchen_sink/kitchen_sink.proto
These are the protos that will be used for the upgraded version of kitchen sink, which will be capable of executing arbitrarily generated workflow definitions
> Initial proto definitions for fuzzy workflow

- cmd/cmdoptions/client.go
This PR adds the `--authorization-env-var` option.
It can be used as `--authorization-env-var TEMPORAL_CLI_AUTH` to authenticate Omes with a token stored in the `TEMPORAL_CLI_AUTH` env var, which would be passed in `Authorization` gRPC metadata.
1. How was this tested:
I ran some benchmarks using `run-scenario` command.
2. Any docs updates needed?
Probably not. I suppose the description in `--help` output is enough.
> Introduce --auth-header option along with TEMPORAL_OMES_AUTH_HEADER env var

- .github/workflows/all-docker-images.yml
- .github/workflows/docker-images.yml
- Use docker PAT instead of password
- Fix "py" / "python" confusion
- Stop using non-standard "ver" abbreviation
Successful run: https://github.com/temporalio/omes/actions/runs/7251630717
> Fix docker build pipeline

- cmd/prepare_worker.go
- dockerfiles/typescript.Dockerfile
- go.mod
- go.sum
Make sure protos get built for the docker file
> TS docker fixes

- loadgen/generic_executor.go
- loadgen/generic_executor_test.go
Late review fixes for https://github.com/temporalio/omes/pull/66
> Add some late review fixes to new timeout flag

- scenarios/throughput_stress.go
Wrapped error to mention search attributes.
Without this it was impossible to know what request was getting permission denied.
1. Closes 
> Improve error message when adding search attribute fails.

- scenarios/throughput_stress.go
Correct error handling for Search Attribute errors.
> Fix log message.

- cmd/cmdoptions/metrics.go
The metrics code was not correctly managing Prometheus collectors.
> Rewire metrics.

- .github/workflows/ci.yml
- .github/workflows/docker-images.yml
Realized the docker CI builds on main were failing b/c of this.
> Fix versions for build all images

- cmd/prepare_worker.go
Omes apparently had main unprotected from admins. Oops.
> Fix issues I managed to just push to main

- dockerfiles/typescript.Dockerfile
- workers/dotnet/Temporalio.Omes.csproj
Verified working here: https://github.com/temporalio/sdk-typescript/actions/runs/10276182026/job/28436402797
> Add rust to TS image to help with building from path

- dockerfiles/go.Dockerfile
- go.mod
- workers/go/go.mod
> Bump Go to 1.24

- loadgen/throughputstress/throughput_stress.go
- scenarios/throughput_stress.go
- workers/go/throughputstress/activities.go
> Fix sleep activity NPE

- scenarios/throughput_stress.go
Some tweaks to the previous PR https://github.com/temporalio/omes/pull/143
I decided to make the scenario take care of tracking the state exactly after all, as it allows the caller to be oblivious to its inner details.
Using it like this
> Make throughputStress resumable (part 2)

- workers/go/throughputstress/workflow.go
Set activity `StartToCloseTimeout` based on Workflow timeout.
I [had removed the StartToCloseTimeout](https://github.com/temporalio/omes/pull/146) but now learned that it's required ...
```
BadScheduleActivityAttributes: A valid StartToClose or ScheduleToCloseTimeout is not set on ScheduleActivityTaskCommand.
```
This time around I ran it locally and confirmed this works.
1. Closes 
> Set StartToCloseTimeout in ThroughputStressWorkflow

- workers/go/throughputstress/workflow.go
Tweaked the ThroughputStress workflow.
_PS: Note that I can't test PRs of Omes Workflow changes in our CICD pipeline since that requires Docker images; which are not built for PRs._
(1) Improved Signal handling to address warning logs about unhandled signals.
(2) Improved handling of Continue-as-New corner case to prevent error.
1. Closes 
> Tweak ThroughputStress workflow

- loadgen/helpers.go
- loadgen/helpers_test.go
(1) New distribution value type float32.
(2) New distribution type "fixed" that always returns the same value.
(3) Expanded existing validation to all types.
PS: This was all AI generated and reviewed/tweaked by me.
(1) To support fairness weights.
(2) To allow specifying a constant value when no distribution is actually needed.
1. Closes 
> Float distribution value and fixed distribution type

- .github/workflows/ci.yml
Added JUnit report and GitHub summary. Borrowed from https://github.com/temporalio/temporal.
So you don't have to dig through the GHA logs.
1. Closes 
> JUnit test summary

- README.md
- loadgen/helper_testenv.go
- loadgen/kitchen_sink_executor_test.go
- loadgen/kitchensink/helpers.go
- scenarios/throughput_stress_test.go
- workers/go/kitchensink/kitchen_sink.go
- workers/java/io/temporal/omes/KitchenSinkWorkflowImpl.java
(1) Test Nexus support
(2) Test (and fix) ChildWorkflow ID support
Needed for kitchensink port of throughout_stress.
1. Closes 
> Test Nexus + ChildWorkflow ID

- .github/workflows/docker-images.yml
Don't use GHA var interpolation directly.
It's a command Injection vulnerability. (reported by Security)
1. Closes SDK-4256
> Fix GHA variable interpolation

- cmd/list_scenarios.go
- cmd/run_scenario.go
- loadgen/scenario.go
- scenarios/ebb_and_flow.go
- scenarios/fixed_resource_consumption.go
- scenarios/fuzzer.go
- scenarios/fuzzer_example.go
- scenarios/state_transitions_steady.go
- scenarios/throughput_stress.go
- scenarios/workflow_on_many_task_queues.go
- scenarios/workflow_with_many_actions.go
- scenarios/workflow_with_single_noop_activity.go
Use a factory function for creating new executors.
Ensure that executor is new; ie without any previous state.
1. Closes 
> Executor factory

- scenarios/throughput_stress.go
Consolidated throughput_stress stats log into single log.
Easier to read in log viewer.
1. Closes 
> Single log for throughput_stress stats

- cmd/cmdoptions/logging.go
- go.mod
- go.sum
- loadgen/ebbandflow/ebb_and_flow.go
- loadgen/ebbandflow/fairness_tracker.go
- loadgen/helpers.go
- loadgen/kitchen_sink_executor_test.go
- scenarios/ebb_and_flow.go
- scenarios/ebb_and_flow_test.go
- scenarios/throughput_stress.go
- scenarios/throughput_stress_test.go
- workers/go/ebbandflow/activities.go
- workers/go/ebbandflow/workflow.go
- workers/go/go.mod
- workers/go/go.sum
- workers/run.go
- workers/test_env.go
- workers/test_workers.go
- added resume capability
- added visibility check for failed workflows
- added integration test
Make it more robust for regular CICD runs.
1. Closes 
> Improve EbbAndFlow scenario

- .github/workflows/all-docker-images.yml
- .github/workflows/ci.yml
- .github/workflows/docker-images.yml
- cmd/build_cli_image.go
- cmd/build_helper.go
- cmd/build_worker_image.go
- cmd/main.go
- dockerfiles/cli.Dockerfile
Publish a Docker image for the CLI (including kitchen-sink-gen).
Useful when running in a CICD environment to not have to build it from scratch. (esp. with the Rust dependency)
1. Closes 
> Omes CLI Docker image

- scenarios/throughput_stress.go
Added Update-with-Start to throughput_stress scenario.
More features coverage.
1. Closes 
> Update-with-Start in TPS

- .github/workflows/all-docker-images.yml
- .github/workflows/docker-images.yml
WISOTT
Reasonable default. Makes integration with other repos easier.
1. Closes 
> Default CI to build/push worker image
